### ISSUE TITLE
Get it to work with Rom::Repository

### ISSUE THREAD

**Issue by JonasFromell** [rom-rb/rom-mongo#13]
Tried to use this adapter with the guide to repositories on rom-rb-org only to find it does not work. Read up a bit and rom-sql seems to work with repositories but i can't find out how/why. Any pointers?
##

**Comment by wafcio** [comment]
I am using it with rom-repository, you should use version from github (master branch). Released version doesn't work with rom-repository.

**Comment by flash-gordon** [comment]
@wafcio I'll release it today

**Comment by flash-gordon** [comment]
0.2.0 is on rubygems.org
